title:              Søren's Social Data Science
email:              s164521@student.dtu.dk
description:        Welcome to my webpage build for the course Social Data Analysis and Visualization 02806, Technical University of Denmark. My name is Søren Blatt Bendtsen, I'm a MSc Business Analytics student, and I'm here to tell you some awesome stories based on data visualization.
author:             Søren Blatt Bendtsen
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   
github_username:      SorenBlattBendtsen
facebook_username:  
instagram_username:  
linkedin_username:    søren-blatt-bendtsen-234062149

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-youtube
  - jekyll-spaceship
  - jekyll-latex

sass:
  sass_dir: _sass
  style: compressed
